### ISSUE TITLE
Build for windows 

### ISSUE THREAD

**Issue by iainctduncan** [iainctduncan/csound_max#1]
discussion thread for the windows build help

**Comment by rorywalsh** [comment]
Arrghhh, I thought you were already using CMake 😬  Right now I don't have time to try to work out a Windows build based on the XCode project. Have you considered switching the build system to CMake? It would make life a lot easier for cross compiling.

**Comment by iainctduncan** [comment]
hi Rory, we can (and should!) definitely switch to the cmake based new Max SDK, I just haven't done it yet. We need to do this anyway to build for M1. There's a video on doing it from Cycling 74 here: https://www.youtube.com/watch?v=il5WblTBUgs&ab_channel=Cycling%2774

**Comment by rorywalsh** [comment]
I haven't used max in 20 years, and won't be using it in the next 20 😆  But I'm happy to help the Csound community if I can. Once you have a Cmake build up and running for Mac I can have a look at getting it going on Windows :+1: But without the Cmake system in place, it would be way too time consuming :(

**Comment by iainctduncan** [comment]
ah, got it. I can respond here again after getting it to build with the new sdk and cmake.

**Comment by stekyne** [comment]
https://github.com/mulle-nat/mulle-xcode-to-cmake maybe you could use this to get 80% of the cmake written and we can help fix it up then? It's most likely quite straightforward anyways no?

**Comment by iainctduncan** [comment]
I can get it to building with Cmake by following the Cycling 74 instructions, I just hadn't done this as I started on this quite a while ago when that was brand new. I'll update folks once that's done.

**Comment by iainctduncan** [comment]
Mind you, if anyone reading this wants to do that, go ahead and then make a pull request! :-)

**Comment by iainctduncan** [comment]
Hi Rory and Stephen, I have now switched this over to CMake, and have it building successfully using Cmake on intel mac. However, I'm getting errors on windows with it failing to find the csound headers using either find_package or find_path. If you are able to take a look at my CMakeLists.txt and have any suggestions that would be great.

**Comment by iainctduncan** [comment]
Working, huzzah! Probably the cmake is hacky, but it's building on both windows and mac now. Will be able to do M1 Real Soon Now.

**Comment by rorywalsh** [comment]
Wow, that was fast!

**Comment by iainctduncan** [comment]
thanks! It's building. I don't like the fact that I couldn't make find_package work and thus had to change how csound is included in the C code accordingly, but I suppose that doesn't matter. I guess anyone who wants to build on their own systems will have an easy time changing the cmake stuff.

Boy is it nicer than having to figure out where the heck stuff is in VS or Xcode! I'm a fan now.

**Comment by rorywalsh** [comment]
I know. It's a real time saver!
