### ISSUE TITLE
Not working on latest version of max msp ? 

### ISSUE THREAD

**Issue by guillaume-leo** [iainctduncan/csound_max#4]
I've the 8.5.7 version of max msp on windows and the object is red, with this message in the console:
Error 126 loading external csound6~

**Comment by iainctduncan** [comment]
Hi Guillaume-leo, couple of questions:
- was this previously working on the same machine with the same csound install on a different Max version?
- have you changed your csound install at all?

I don't run windows so hard for me to verify, but if it is an issue with the object it would be good to know

**Comment by guillaume-leo** [comment]
I've reinstalled csound and it's working.. my bad

**Comment by iainctduncan** [comment]
No worries, good to know!
